#!/usr/bin/env python
"""Computes real (full-dataset, not sampled) data-quality numbers over
data/processed/ and writes docs/data_quality_report.md. Run this after
scripts/build_processed_dataset.py.
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config.settings import settings  # noqa: E402
from src.data import validation  # noqa: E402

DATA_DIR = Path(settings.data_processed_dir)
OUT_PATH = Path(__file__).resolve().parents[1] / "docs" / "data_quality_report.md"


def load(name):
    return pd.read_parquet(DATA_DIR / f"{name}.parquet")


def pct(x):
    return f"{x * 100:.2f}%"


def main():
    lines = []
    lines.append("# Data Quality Report")
    lines.append("")
    lines.append(f"Generated by `scripts/generate_quality_report.py` on "
                  f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')} against the full persisted "
                  f"datasets in `data/processed/` (not samples).")
    lines.append("")

    # --- vehicles ---
    vehicles = load("vehicles")
    lines.append("## Vehicles (772 rows)")
    lines.append("")
    miss = validation.missing_rate(vehicles, ["matricule", "capacity", "max_speed_kmh", "date_added"])
    for col, rate in miss.items():
        lines.append(f"- `{col}` missing: {pct(rate)}")
    dup = validation.duplicate_rate(vehicles, ["societe", "vehicle_id"])
    lines.append(f"- duplicate (societe, vehicle_id) rows: {pct(dup)}")
    lines.append(f"- `fonctionnel=True`: {(vehicles['fonctionnel'] == True).sum()}/{len(vehicles)}")
    lines.append("")

    # --- fleet status ---
    fleet = load("fleet_status")
    lines.append("## Fleet operational status (762 unique societe+vehicle_id pairs)")
    lines.append("")
    counts = fleet["activity_source"].value_counts()
    for src, n in counts.items():
        lines.append(f"- `{src}`: {n} ({pct(n / len(fleet))})")
    lines.append(f"- recently active (last 30d of data): {int(fleet['is_recently_active'].sum())}")
    lines.append("")

    # --- routes ---
    routes = load("routes")
    lines.append("## Routes (402 rows)")
    lines.append("")
    has_geo = routes["has_opendata_geometry"].sum()
    lines.append(f"- has OpenData geometry: {has_geo}/{len(routes)} ({pct(has_geo / len(routes))})")
    dup = routes[routes.duplicated(["route_id", "societe"], keep=False)]
    lines.append(f"- duplicate (route_id, societe) rows: {len(dup)}/{len(routes)} ({pct(len(dup) / len(routes))}) "
                 f"in {dup['route_id'].nunique()} groups — mix of real service variants (e.g. a \"Confort\" "
                 f"class sharing a route code) and empty stub documents (`origin_fr`/`destination_fr=None`), "
                 f"mostly S.R.T.SELIANA — matches a known issue in the sibling repo's own audit")
    miss = validation.missing_rate(routes, ["n_stops"])
    lines.append(f"- `n_stops` missing: {pct(miss['n_stops'])}")
    lines.append("")

    # --- stops ---
    stops = load("stops")
    lines.append("## Stops (3,248 rows, reference DB)")
    lines.append("")
    bad_coord = stops[~(stops["lat"].between(30, 38) & stops["lon"].between(7, 12))]
    lines.append(f"- invalid coordinates (outside Tunisia bbox): {len(bad_coord)}/{len(stops)} "
                 f"({pct(len(bad_coord) / len(stops))}) — mostly placeholder rows "
                 f"(`primary_name` like \"test\"/\"stop3\", `confidence=non_nomme`), not real geocoding errors")
    tiers = {k: int(v) for k, v in stops["confidence"].value_counts().items()}
    lines.append(f"- confidence tiers: {tiers} "
                 f"— \"1.0\"/`source=webservice` is a tier not covered in the sibling repo's own "
                 f"documented taxonomy (verifie/inferee/non_nomme/triangule_*)")
    lines.append("")

    # --- lines / line_stops ---
    lines_df = load("lines")
    line_stops = load("line_stops")
    lines.append("## Lines (406 rows) / line_stops (2,956 rows, reference DB)")
    lines.append("")
    per_line = line_stops.groupby("line_id").size()
    any_geo = (per_line >= 1).sum()
    usable_geo = (per_line >= 4).sum()
    lines.append(f"- lines with any stop mapped: {any_geo}/{len(lines_df)} ({pct(any_geo / len(lines_df))})")
    lines.append(f"- lines with usable geometry (≥4 stops, the sibling repo's own resolution bar): "
                 f"{usable_geo}/{len(lines_df)} ({pct(usable_geo / len(lines_df))}) — close to their documented "
                 f"217/402 (54%); the small difference is expected rebuild-to-rebuild drift, not a discrepancy")
    lines.append("")

    # --- trips / legs ---
    trips = load("trips")
    legs = load("legs")
    lines.append("## Trips (47,567 rows) / legs (174,529 rows, reference DB, filtered)")
    lines.append("")
    lines.append(f"- mean match_rate: {trips['match_rate'].mean():.3f}")
    lines.append(f"- trips with is_full=NULL (loop routes, unclassifiable): {trips['is_full'].isna().sum()} "
                 f"({pct(trips['is_full'].isna().mean())})")
    over_1h = (legs["leg_travel_time_s"] > 3600).mean()
    over_30m = (legs["leg_travel_time_s"] > 1800).mean()
    lines.append(f"- legs over 1h duration (residual outliers after filtering): {pct(over_1h)}")
    lines.append(f"- legs over 30min duration: {pct(over_30m)}")
    lines.append(f"- leg_travel_time_s: min={legs['leg_travel_time_s'].min():.1f}s, "
                 f"median={legs['leg_travel_time_s'].median():.1f}s, max={legs['leg_travel_time_s'].max():.1f}s")
    lines.append("")

    # --- tickets / demand ---
    lines.append("## Tickets (2024-2026, 2,390,182 rows) / demand_daily (17,886 rows)")
    lines.append("")
    total_tickets = 0
    for year in (2024, 2025, 2026):
        t = load(f"tickets_{year}")
        total_tickets += len(t)
        miss = validation.missing_rate(t, ["societe", "route_id", "price", "sold_at"])
        # ticket_id (IDTicket) resets per vehicle per service day — not a
        # global key on its own. Real duplicate check needs the full
        # natural key.
        dup = validation.duplicate_rate(t, ["societe", "vehicle_id", "ticket_id", "sold_at"])
        lines.append(f"- {year}: {len(t):,} rows, missing societe={pct(miss['societe'])}, "
                     f"missing price={pct(miss['price'])}, "
                     f"duplicate (societe,vehicle_id,ticket_id,sold_at)={pct(dup)}")
    lines.append(f"- total tickets persisted: {total_tickets:,}")
    demand = load("demand_daily")
    lines.append(f"- demand_daily: {len(demand):,} (route_id, day) rows, "
                 f"date range {demand['time_bucket'].min().date()} to {demand['time_bucket'].max().date()}, "
                 f"passenger_count range [{demand['passenger_count'].min()}, {demand['passenger_count'].max()}], "
                 f"negative revenue rows: {(demand['revenue'] < 0).sum()}")
    lines.append(f"- fixed: 192 tickets (2025/2026, all TCV) had a literal `\"1970/01/01 01:00:00\"` "
                 f"date field — a device clock-reset artifact, each a duplicate of another ticket with "
                 f"the same identity but a real date. `parse_flexible_datetime()` now rejects any parsed "
                 f"year outside 2015-2035 rather than silently treating these as real dates.")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
