#!/usr/bin/env python
"""Runs the vehicle allocation optimizer against persisted data and
writes the result to docs/optimization_results.md.

Decisions made here:
- Only the 4 companies with a recently-active operational fleet are
  considered (S.R.T.K, S.R.T.SELIANA, S.T.S, SRT.ELGOUAFEL — see
  fleet_status.parquet / docs/optimization_problem.md Problem 2). Other
  companies have 0 operational vehicles in this data and are excluded,
  not silently given phantom capacity.
- predicted_demand per route = that route's mean daily passenger_count
  over its last 30 observed days in demand_daily.parquet. The trained
  demand model (models/demand/histgb_v1.joblib) exists and beats this
  naive estimate for next-day forecasts (see baseline_results.md), but
  generating a proper multi-route one-step-ahead feature row for every
  route here is a separate step not worth the added risk for this pass
  — recent realized average is a robust, already-validated input to
  demonstrate the optimizer itself. Swapping in real forecasts later is
  a one-line change to how `predicted_demand` is built below.
- Vehicles are allocated as a per-company fungible count per route (not
  specific vehicle IDs) — see src/optimization/vehicle_optimizer.py.

Run: python scripts/run_vehicle_allocation.py
"""

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config.settings import settings  # noqa: E402
from src.optimization import vehicle_optimizer  # noqa: E402

RECENT_DAYS = 30
OUT_PATH = Path(__file__).resolve().parents[1] / "docs" / "optimization_results.md"


def _to_markdown(df: pd.DataFrame) -> str:
    """Plain markdown table, no `tabulate` dependency."""
    header = "| " + " | ".join(str(c) for c in df.columns) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    rows = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, sep] + rows)


def main():
    data_dir = Path(settings.data_processed_dir)
    fleet_status = pd.read_parquet(data_dir / "fleet_status.parquet")
    vehicles = pd.read_parquet(data_dir / "vehicles.parquet")
    vehicles["vehicle_id"] = vehicles["vehicle_id"].astype(str)
    routes = pd.read_parquet(data_dir / "routes.parquet")
    demand = pd.read_parquet(data_dir / "demand_daily.parquet")

    op = fleet_status[fleet_status["is_recently_active"] == True]
    op = op.merge(vehicles[["societe", "vehicle_id", "capacity"]], on=["societe", "vehicle_id"], how="left")
    fleet = (
        op.groupby("societe")
        .agg(available_vehicles=("vehicle_id", "count"), avg_capacity=("capacity", "mean"))
        .reset_index()
    )
    print("Operational fleet by company:")
    print(fleet.to_string(index=False))

    companies_with_fleet = set(fleet["societe"])
    r_societe = routes[["route_id", "societe"]].drop_duplicates()
    d = demand.merge(r_societe, on="route_id", how="left")
    d = d[d["societe"].isin(companies_with_fleet)]

    cutoff = d.groupby("route_id")["time_bucket"].transform("max") - pd.Timedelta(days=RECENT_DAYS)
    recent = d[d["time_bucket"] > cutoff]
    route_demand = (
        recent.groupby(["route_id", "societe"])["passenger_count"]
        .mean()
        .reset_index()
        .rename(columns={"passenger_count": "predicted_demand"})
    )
    print(f"\n{len(route_demand)} routes with demand across {route_demand['societe'].nunique()} operational companies")

    result = vehicle_optimizer.allocate_vehicles(route_demand, fleet)

    print(f"\nsolver status: {result.attrs['solver_status']}, total shortfall: {result.attrs['objective_total_shortfall']:.0f}")
    print(result.sort_values("predicted_demand", ascending=False).head(10).to_string(index=False))

    total_demand = result["predicted_demand"].sum()
    total_covered = result["capacity_provided"].sum()
    overall_coverage = total_covered / total_demand

    lines = []
    lines.append("# Vehicle Allocation — Optimization Result")
    lines.append("")
    lines.append(f"Generated by `scripts/run_vehicle_allocation.py`. OR-Tools CP-SAT, "
                 f"solver status: **{result.attrs['solver_status']}**.")
    lines.append("")
    lines.append("## Operational fleet used")
    lines.append("")
    lines.append(_to_markdown(fleet.round(1)))
    lines.append("")
    lines.append(f"## Result: {len(result)} routes, {int(fleet['available_vehicles'].sum())} vehicles available")
    lines.append("")
    lines.append(f"- Total predicted daily demand: {total_demand:.0f} passengers")
    lines.append(f"- Total capacity provided by this allocation: {total_covered:.0f} passengers "
                 f"({overall_coverage * 100:.1f}% coverage)")
    lines.append(f"- Total shortfall (minimized objective): {result.attrs['objective_total_shortfall']:.0f} passengers")
    lines.append(f"- Routes fully covered (shortfall=0): {(result['shortfall'] == 0).sum()}/{len(result)}")
    lines.append(f"- Routes with zero vehicles assigned: {(result['assigned_vehicles'] == 0).sum()}/{len(result)}")
    lines.append("")
    lines.append("## Full allocation (sorted by predicted demand)")
    lines.append("")
    lines.append("Note: `route_id` is not unique across companies (confirmed, see "
                 "docs/database.md) — e.g. route \"220\" below is two unrelated routes, "
                 "one each for S.R.T.K and S.T.S, allocated independently.")
    lines.append("")
    display_cols = ["route_id", "societe", "predicted_demand", "assigned_vehicles", "capacity_provided", "shortfall", "coverage_ratio"]
    lines.append(_to_markdown(result[display_cols].sort_values("predicted_demand", ascending=False).round(1)))
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(f"With only {int(fleet['available_vehicles'].sum())} vehicles confirmed operational across "
                 f"{fleet['societe'].nunique()} companies (see docs/reference_db_integration.md — 70% of the "
                 f"772-vehicle roster shows no activity signal at all), this fleet covers "
                 f"{overall_coverage * 100:.0f}% of predicted demand on these routes even under an optimal "
                 f"allocation. This is a real capacity constraint, not a solver artifact — the business question "
                 f"this surfaces is whether the true operational fleet is actually this small, or whether "
                 f"`winicari.bus`/activity tracking needs fixing before allocation planning can be trusted "
                 f"(see docs/roadmap.md, item 1).")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {OUT_PATH}")


if __name__ == "__main__":
    main()
