#!/usr/bin/env python
"""Trains and evaluates the demand-forecasting baseline against the
naive last-week rule, on the persisted data/processed/demand_daily.parquet.

Decisions made here (documented, not asked, per project scope):
- Only routes with >=200 daily observations are included (33/106 routes,
  16,062/17,884 rows) — routes with sparser history can't support a
  meaningful lag-7/train-test evaluation.
- Test = each route's last 56 days (8 weeks) within its own observed
  range; train = everything before that, per route.
- Both the naive baseline and the model are scored on the exact same
  test rows (those with a non-null lag_7), for a fair comparison.

Run: python scripts/train_demand_baseline.py
"""

import sys
from pathlib import Path

import joblib
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config.settings import settings  # noqa: E402
from src.data import transformations  # noqa: E402
from src.features import demand_features  # noqa: E402
from src.models import demand_forecasting  # noqa: E402
from src.evaluation import forecasting_metrics  # noqa: E402

MIN_ROWS_PER_ROUTE = 200
TEST_DAYS = 56
MODEL_OUT = Path(__file__).resolve().parents[1] / "models" / "demand" / "histgb_v1.joblib"
REPORT_OUT = Path(__file__).resolve().parents[1] / "docs" / "baseline_results.md"


def main():
    demand = pd.read_parquet(Path(settings.data_processed_dir) / "demand_daily.parquet")

    counts = demand.groupby("route_id").size()
    eligible = counts[counts >= MIN_ROWS_PER_ROUTE].index
    demand = demand[demand["route_id"].isin(eligible)].copy()
    print(f"{len(eligible)} routes eligible (>= {MIN_ROWS_PER_ROUTE} rows), {len(demand)} rows total")

    demand = transformations.fill_demand_calendar_gaps(demand)
    print(f"after calendar-gap fill: {len(demand)} rows")

    demand = demand_features.add_calendar_features(demand)
    demand = demand_features.add_lag_features(demand, lags=(1, 7))
    demand["route_id"] = demand["route_id"].astype("category")

    scored = demand.dropna(subset=["passenger_count_lag_1", "passenger_count_lag_7"]).copy()

    cutoffs = scored.groupby("route_id", observed=True)["time_bucket"].transform("max") - pd.Timedelta(days=TEST_DAYS)
    train_df = scored[scored["time_bucket"] <= cutoffs]
    test_df = scored[scored["time_bucket"] > cutoffs]
    print(f"train: {len(train_df)} rows, test: {len(test_df)} rows")

    baseline_pred = test_df["passenger_count_lag_7"]
    y_true = test_df["passenger_count"]

    model = demand_forecasting.train(train_df)
    model_pred = demand_forecasting.predict(model, test_df)

    results = {
        "naive_last_week": {
            "mae": forecasting_metrics.mae(y_true, baseline_pred),
            "rmse": forecasting_metrics.rmse(y_true, baseline_pred),
            "mape": forecasting_metrics.mape(y_true, baseline_pred),
        },
        "histgb": {
            "mae": forecasting_metrics.mae(y_true, model_pred),
            "rmse": forecasting_metrics.rmse(y_true, model_pred),
            "mape": forecasting_metrics.mape(y_true, model_pred),
        },
    }

    for name, m in results.items():
        print(f"{name}: MAE={m['mae']:.2f}  RMSE={m['rmse']:.2f}  MAPE={m['mape']:.3f}")

    improvement = (results["naive_last_week"]["mae"] - results["histgb"]["mae"]) / results["naive_last_week"]["mae"]
    print(f"MAE improvement over baseline: {improvement * 100:.1f}%")

    MODEL_OUT.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, MODEL_OUT)
    print(f"wrote {MODEL_OUT}")

    verdict = ("beats the naive baseline by a meaningful margin — worth keeping"
               if improvement > 0.10 else
               "does NOT clearly beat the naive baseline — the naive rule is the better default here")

    report = f"""# Baseline Results — Demand Forecasting

Generated by `scripts/train_demand_baseline.py` against
`data/processed/demand_daily.parquet` ({len(eligible)} routes with
>={MIN_ROWS_PER_ROUTE} daily observations, {len(scored)} scoreable rows
after calendar-gap fill and lag computation).

Train: everything before each route's last {TEST_DAYS} days.
Test: each route's last {TEST_DAYS} days ({len(test_df)} rows).

| Model | MAE | RMSE | MAPE |
|---|---|---|---|
| Naive last-week (t-7) | {results['naive_last_week']['mae']:.2f} | {results['naive_last_week']['rmse']:.2f} | {results['naive_last_week']['mape']:.3f} |
| HistGradientBoostingRegressor | {results['histgb']['mae']:.2f} | {results['histgb']['rmse']:.2f} | {results['histgb']['mape']:.3f} |

MAE improvement over baseline: {improvement * 100:.1f}%.

**Verdict: the model {verdict}.**

MAPE is high (>1.0) for both models — expected, not a bug: these 33
routes range from ~13 to ~2,841 daily passengers (median 49), and MAPE
blows up on the low-volume end (a miss of 3 on a true value of 1 is a
300% error). MAE/RMSE are the more meaningful metrics here given that
spread; a per-route-normalized or log-scale target would likely tame
MAPE further but wasn't needed to answer "does a learned model beat the
naive rule."

Model artifact: `models/demand/histgb_v1.joblib`.
"""
    REPORT_OUT.write_text(report, encoding="utf-8")
    print(f"wrote {REPORT_OUT}")


if __name__ == "__main__":
    main()
